In [2]:
import numpy as np
import timeit

A = np.array([[8, 7, 6], [5, 4, 3], [2, 1, 0]])
print(A)

B = np.arange(9).reshape(3, 3)
print(B)

[[8 7 6]
 [5 4 3]
 [2 1 0]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
C = A @ B
# C = A.dot(B)

print(C)

[[57 78 99]
 [30 42 54]
 [ 3  6  9]]


In [4]:
def matrix_multiplication_b(A, B):
    n = A.shape[0]
    C = np.zeros((n, n), dtype=A.dtype)

    for row in range(n):
        for col in range(n):
            for i in range(n):
                C[row, col] += A[row, i] * B[i, col]

    return C

print(matrix_multiplication_b(A, B))

[[57 78 99]
 [30 42 54]
 [ 3  6  9]]


In [5]:
def matrix_multiplication_c(A, B):
    n = A.shape[0]
    C = np.zeros((n, n), dtype=A.dtype)

    for col in range(n):
        for row in range(n):
            for i in range(n):
                C[row, col] += A[row, i] * B[i, col]

    return C

print(matrix_multiplication_c(A, B))

[[57 78 99]
 [30 42 54]
 [ 3  6  9]]


In [6]:
def matrix_multiplication_d(A, B):
    n = A.shape[0]
    C = np.zeros((n, n), dtype=int)
    for col in range(n):
        for row in range(n):
            C[row, col] = np.sum(A[row, :] * B[:, col])

    return C

print(matrix_multiplication_d(A, B))

[[57 78 99]
 [30 42 54]
 [ 3  6  9]]


In [7]:
def matrix_multiplication_e(A, B):
    n = A.shape[0]
    A_T = A.T
    C = np.zeros((n, n), dtype=A.dtype)
    for row in range(n):
        for col in range(n):
            C[row, col] = np.sum(A_T[:, row] * B[:, col])
    return C

print(matrix_multiplication_e(A, B))

[[57 78 99]
 [30 42 54]
 [ 3  6  9]]


In [8]:
def matrix_multiplication_f(A, B):
    n = B.shape[0]
    B_T = B.T
    C = np.zeros((n, n), dtype=B.dtype)
    for row in range(n):
        for col in range(n):
            C[row, col] = np.sum(A[row, :] * B_T[col, :])
    return C

print(matrix_multiplication_f(A, B))

[[57 78 99]
 [30 42 54]
 [ 3  6  9]]


In [9]:
A10 = np.arange(100).reshape(10, 10)
print(A10)

B10 = np.arange(100).reshape(10, 10)
print(B10)

C10 = A10 @ B10
# C = A.dot(B)

print(C10)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 2850  2895  2940  2985  3030  3075  3120  3165  3210  3255]
 [ 7350  7495  7640  7785  7930  8075  8220  8365  8510  8655]
 [11850 12095 12340 12585 12830 13075 13320 13565 13810 14055]
 [16350 16695 17040 17385 17730 18075 18420 18765 19110 19455]
 [20850 21295 21740 22185 22630 23075 23520 23965 24410 24855]
 [25350 25895 26440 269

In [10]:
print(timeit.timeit(lambda: matrix_multiplication_b(A10, B10), number=1))
print(timeit.timeit(lambda: matrix_multiplication_c(A10, B10), number=1))
print(timeit.timeit(lambda: matrix_multiplication_d(A10, B10), number=1))
print(timeit.timeit(lambda: matrix_multiplication_e(A10, B10), number=1))
print(timeit.timeit(lambda: matrix_multiplication_f(A10, B10), number=1))

0.0003009590000147
0.0002922919957200065
0.00024020799901336432
0.00021158400340937078
0.000203875002625864


In [11]:
A100 = np.arange(10000).reshape(100, 100)

B100 = np.arange(10000).reshape(100, 100)

C100 = A100 @ B100

In [12]:
print(timeit.timeit(lambda: matrix_multiplication_b(A100, B100), number=1))
print(timeit.timeit(lambda: matrix_multiplication_c(A100, B100), number=1))
print(timeit.timeit(lambda: matrix_multiplication_d(A100, B100), number=1))
print(timeit.timeit(lambda: matrix_multiplication_e(A100, B100), number=1))
print(timeit.timeit(lambda: matrix_multiplication_f(A100, B100), number=1))

0.29044791699561756
0.2647143340000184
0.020456416998058558
0.019505791999108624
0.01981129100022372


In [3]:
A1000 = np.arange(1000000).reshape(1000, 1000)

B1000 = np.arange(1000000).reshape(1000, 1000)

C1000 = A1000 @ B1000

In [1]:
print(timeit.timeit(lambda: matrix_multiplication_b(A1000, B1000), number=1))
print(timeit.timeit(lambda: matrix_multiplication_c(A1000, B1000), number=1))
print(timeit.timeit(lambda: matrix_multiplication_d(A1000, B1000), number=1))
print(timeit.timeit(lambda: matrix_multiplication_e(A1000, B1000), number=1))
print(timeit.timeit(lambda: matrix_multiplication_f(A1000, B1000), number=1))

NameError: name 'timeit' is not defined

In [4]:
print(timeit.timeit(lambda: (A1000 * B1000), number=1))

0.0017962090205401182
